### PR TITLE
Add sticker

### PR DESCRIPTION
**Pull request by ateucher**

### CODE REVIEW

**Review by BonnieJRobert — APPROVED** [review]
Looks good, Andy!

**Review by stephhazlitt — APPROVED** [review]
💯💙

**Review by MonkmanMH — APPROVED** [review]
This is fantastic.

**Review by boshek — APPROVED** [review]
A thing of beauty

**Comment by ateucher** [comment]
I added the sticker and badges to the readme, and am working on a way to ignore those for ocwa import.

**Comment by MonkmanMH** [comment]
I'll be ordering some from the UVic print shop...I will let you know when they are reality

**Comment by ateucher** [comment]
Ok I'm going to merge this, then do the ocwa import on a new branch

**Pull request merged**
